#pragma config(Motor,  port2,           FrontRightDrive, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           BackRightDrive, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           BackLeftDrive, tmotorVex393, openLoop, encoder, encoderPort, None, 1000)
#pragma config(Motor,  port5,           FrontLeftDrive, tmotorVex393, openLoop, encoder, encoderPort, None, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
	bool meep = true;
	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................
		motor[FrontLeftDrive] = 127;
	  motor[FrontRightDrive] = 127;
		motor[BackLeftDrive] = 127;
		motor[BackRightDrive] = 127;
		wait1Msec(1000);
		motor[FrontLeftDrive] = 0;
	  motor[FrontRightDrive] = 0;
		motor[BackLeftDrive] = 0;
		motor[BackRightDrive] = 0;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop
	int r = 0;
	int y = 0;
	int x = 0;
	while (true)
	{
		r = vexRT[Ch1];
		y = vexRT[Ch3];
		x = vexRT[Ch4];
		//motor[Right] = y - r;
		//motor[Left] = y + r;
		motor[FrontLeftDrive] = y + x + r;
	  motor[FrontRightDrive] = y - x - r;
		motor[BackLeftDrive] = y - x + r;
		motor[BackRightDrive] = y + x - r;
		wait1Msec(50);
	}
}
